import type { Signal } from './blueprint.d.ts';

export const Signals: Record<string, Signal> = {
    WoodenChest: { 'name': 'wooden-chest' },
    IronChest: { 'name': 'iron-chest' },
    SteelChest: { 'name': 'steel-chest' },
    StorageTank: { 'name': 'storage-tank' },
    TransportBelt: { 'name': 'transport-belt' },
    FastTransportBelt: { 'name': 'fast-transport-belt' },
    ExpressTransportBelt: { 'name': 'express-transport-belt' },
    TurboTransportBelt: { "name": "turbo-transport-belt" },
    UndergroundBelt: { 'name': 'underground-belt' },
    FastUndergroundBelt: { 'name': 'fast-underground-belt' },
    ExpressUndergroundBelt: { 'name': 'express-underground-belt' },
    TurboUndergroundBelt: { "name": "turbo-underground-belt" },
    Splitter: { 'name': 'splitter' },
    FastSplitter: { 'name': 'fast-splitter' },
    ExpressSplitter: { 'name': 'express-splitter' },
    TurboSplitter: { "name": "turbo-splitter" },
    BurnerInserter: { 'name': 'burner-inserter' },
    Inserter: { 'name': 'inserter' },
    LongHandedInserter: { 'name': 'long-handed-inserter' },
    FastInserter: { 'name': 'fast-inserter' },
    BulkInserter: { "name": "bulk-inserter" },
    StackInserter: { 'name': 'stack-inserter' },
    SmallElectricPole: { 'name': 'small-electric-pole' },
    MediumElectricPole: { 'name': 'medium-electric-pole' },
    BigElectricPole: { 'name': 'big-electric-pole' },
    Substation: { 'name': 'substation' },
    Pipe: { 'name': 'pipe' },
    PipeToGround: { 'name': 'pipe-to-ground' },
    CastingPipe: { "type": "recipe", "name": "casting-pipe" },
    CastingPipeToGround: { "type": "recipe", "name": "casting-pipe-to-ground" },
    Pump: { 'name': 'pump' },
    Rail: { 'name': 'rail' },
    RailRamp: { "name": "rail-ramp" },
    RailSupport: { "name": "rail-support" },
    TrainStop: { 'name': 'train-stop' },
    RailSignal: { 'name': 'rail-signal' },
    RailChainSignal: { 'name': 'rail-chain-signal' },
    Locomotive: { 'name': 'locomotive' },
    CargoWagon: { 'name': 'cargo-wagon' },
    FluidWagon: { 'name': 'fluid-wagon' },
    ArtilleryWagon: { 'name': 'artillery-wagon' },
    Car: { 'name': 'car' },
    Tank: { 'name': 'tank' },
    Spidertron: { 'name': 'spidertron' },
    LogisticRobot: { 'name': 'logistic-robot' },
    ConstructionRobot: { 'name': 'construction-robot' },
    ActiveProviderChest: { 'name': 'active-provider-chest' },
    PassiveProviderChest: { 'name': 'passive-provider-chest' },
    StorageChest: { 'name': 'storage-chest' },
    BufferChest: { 'name': 'buffer-chest' },
    RequesterChest: { 'name': 'requester-chest' },
    Roboport: { 'name': 'roboport' },
    SmallLamp: { 'name': 'small-lamp' },
    ArithmeticCombinator: { 'name': 'arithmetic-combinator' },
    DeciderCombinator: { 'name': 'decider-combinator' },
    SelectorCombinator: { "name": "selector-combinator" },
    ConstantCombinator: { 'name': 'constant-combinator' },
    PowerSwitch: { 'name': 'power-switch' },
    ProgrammableSpeaker: { 'name': 'programmable-speaker' },
    DisplayPanel: { "name": "display-panel" },
    StoneBrick: { 'name': 'stone-brick' },
    Concrete: { 'name': 'concrete' },
    HazardConcrete: { 'name': 'hazard-concrete' },
    RefinedConcrete: { 'name': 'refined-concrete' },
    RefinedHazardConcrete: { 'name': 'refined-hazard-concrete' },
    Landfill: { 'name': 'landfill' },
    ArtificialYumakoSoil: { "name": "artificial-yumako-soil" },
    OvergrowthYumakoSoil: { "name": "overgrowth-yumako-soil" },
    ArtificialJellynutSoil: { "name": "artificial-jellynut-soil" },
    OvergrowthJellynutSoil: { "name": "overgrowth-jellynut-soil" },
    IcePlatform: { "name": "ice-platform" },
    Foundation: { "name": "foundation" },
    CliffExplosives: { 'name': 'cliff-explosives' },
    RepairPack: { 'name': 'repair-pack' },
    Blueprint: { 'name': 'blueprint' },
    DeconstructionPlanner: { 'name': 'deconstruction-planner' },
    UpgradePlanner: { 'name': 'upgrade-planner' },
    BlueprintBook: { 'name': 'blueprint-book' },
    Boiler: { 'name': 'boiler' },
    SteamEngine: { 'name': 'steam-engine' },
    SolarPanel: { 'name': 'solar-panel' },
    Accumulator: { 'name': 'accumulator' },
    NuclearReactor: { 'name': 'nuclear-reactor' },
    HeatPipe: { 'name': 'heat-pipe' },
    HeatExchanger: { 'name': 'heat-exchanger' },
    SteamTurbine: { 'name': 'steam-turbine' },
    FusionReactor: { "name": "fusion-reactor" },
    FusionGenerator: { "name": "fusion-generator" },
    BurnerMiningDrill: { 'name': 'burner-mining-drill' },
    ElectricMiningDrill: { 'name': 'electric-mining-drill' },
    BigMiningDrill: { "name": "big-mining-drill" },
    OffshorePump: { 'name': 'offshore-pump' },
    Pumpjack: { 'name': 'pumpjack' },
    StoneFurnace: { 'name': 'stone-furnace' },
    SteelFurnace: { 'name': 'steel-furnace' },
    ElectricFurnace: { 'name': 'electric-furnace' },
    Foundry: { "name": "foundry" },
    Recycler: { "name": "recycler" },
    AgriculturalTower: { "name": "agricultural-tower" },
    Biochamber: { "name": "biochamber" },
    CaptiveBiterSpawner: { "name": "captive-biter-spawner" },
    AssemblingMachine1: { 'name': 'assembling-machine-1' },
    AssemblingMachine2: { 'name': 'assembling-machine-2' },
    AssemblingMachine3: { 'name': 'assembling-machine-3' },
    OilRefinery: { 'name': 'oil-refinery' },
    ChemicalPlant: { 'name': 'chemical-plant' },
    Centrifuge: { 'name': 'centrifuge' },
    ElectromagneticPlant: { "name": "electromagnetic-plant" },
    CryogenicPlant: { "name": "cryogenic-plant" },
    Lab: { 'name': 'lab' },
    Biolab: { "name": "biolab" },
    LightningRod: { "name": "lightning-rod" },
    LightningCollector: { "name": "lightning-collector" },
    HeatingTower: { "name": "heating-tower" },
    Beacon: { 'name': 'beacon' },
    SpeedModule: { 'name': 'speed-module' },
    SpeedModule2: { 'name': 'speed-module-2' },
    SpeedModule3: { 'name': 'speed-module-3' },
    EfficiencyModule: { 'name': 'efficiency-module' },
    EfficiencyModule2: { 'name': 'efficiency-module-2' },
    EfficiencyModule3: { 'name': 'efficiency-module-3' },
    ProductivityModule: { 'name': 'productivity-module' },
    ProductivityModule2: { 'name': 'productivity-module-2' },
    ProductivityModule3: { 'name': 'productivity-module-3' },
    QualityModule: { "name": "quality-module" },
    QualityModule2: { "name": "quality-module-2" },
    QualityModule3: { "name": "quality-module-3" },
    BasicOilProcessing: { "type": "recipe", "name": "basic-oil-processing" },
    AdvancedOilProcessing: { "type": "recipe", "name": "advanced-oil-processing" },
    SimpleCoalLiquefaction: { "type": "recipe", "name": "simple-coal-liquefaction" },
    CoalLiquefaction: { "type": "recipe", "name": "coal-liquefaction" },
    HeavyOilCracking: { "type": "recipe", "name": "heavy-oil-cracking" },
    LightOilCracking: { "type": "recipe", "name": "light-oil-cracking" },
    SolidFuelFromPetroleumGas: { "type": "recipe", "name": "solid-fuel-from-petroleum-gas" },
    SolidFuelFromLightOil: { "type": "recipe", "name": "solid-fuel-from-light-oil" },
    SolidFuelFromHeavyOil: { "type": "recipe", "name": "solid-fuel-from-heavy-oil" },
    AcidNeutralisation: { "type": "recipe", "name": "acid-neutralisation" },
    SteamCondensation: { "type": "recipe", "name": "steam-condensation" },
    IceMelting: { "type": "recipe", "name": "ice-melting" },
    Wood: { 'name': 'wood' },
    Coal: { 'name': 'coal' },
    Stone: { 'name': 'stone' },
    IronOre: { 'name': 'iron-ore' },
    CopperOre: { 'name': 'copper-ore' },
    UraniumOre: { 'name': 'uranium-ore' },
    RawFish: { 'name': 'raw-fish' },
    Ice: { "name": "ice" },
    IronPlate: { 'name': 'iron-plate' },
    CopperPlate: { 'name': 'copper-plate' },
    SteelPlate: { 'name': 'steel-plate' },
    SolidFuel: { 'name': 'solid-fuel' },
    PlasticBar: { 'name': 'plastic-bar' },
    Sulfur: { 'name': 'sulfur' },
    Battery: { 'name': 'battery' },
    Explosives: { 'name': 'explosives' },
    Carbon: { "name": "carbon" },
    CoalSynthesis: { "type": "recipe", "name": "coal-synthesis" },
    WaterBarrel: { 'name': 'water-barrel' },
    CrudeOilBarrel: { 'name': 'crude-oil-barrel' },
    PetroleumGasBarrel: { 'name': 'petroleum-gas-barrel' },
    LightOilBarrel: { 'name': 'light-oil-barrel' },
    HeavyOilBarrel: { 'name': 'heavy-oil-barrel' },
    LubricantBarrel: { 'name': 'lubricant-barrel' },
    SulfuricAcidBarrel: { 'name': 'sulfuric-acid-barrel' },
    FluoroketoneHotBarrel: { "name": "fluoroketone-hot-barrel" },
    FluoroketoneColdBarrel: { "name": "fluoroketone-cold-barrel" },
    FillWaterBarrel: { "type": "recipe", "name": "water-barrel" },
    FillCrudeOilBarrel: { "type": "recipe", "name": "crude-oil-barrel" },
    FillPetroleumGasBarrel: { "type": "recipe", "name": "petroleum-gas-barrel" },
    FillLightOilBarrel: { "type": "recipe", "name": "light-oil-barrel" },
    FillHeavyOilBarrel: { "type": "recipe", "name": "heavy-oil-barrel" },
    FillLubricantBarrel: { "type": "recipe", "name": "lubricant-barrel" },
    FillSulfuricAcidBarrel: { "type": "recipe", "name": "sulfuric-acid-barrel" },
    FillFluoroketoneHotBarrel: { "type": "recipe", "name": "fluoroketone-hot-barrel" },
    FillFluoroketoneColdBarrel: { "type": "recipe", "name": "fluoroketone-cold-barrel" },
    EmptyWaterBarrel: { "type": "recipe", "name": "empty-water-barrel" },
    EmptyCrudeOilBarrel: { "type": "recipe", "name": "empty-crude-oil-barrel" },
    EmptyPetroleumGasBarrel: { "type": "recipe", "name": "empty-petroleum-gas-barrel" },
    EmptyLightOilBarrel: { "type": "recipe", "name": "empty-light-oil-barrel" },
    EmptyHeavyOilBarrel: { "type": "recipe", "name": "empty-heavy-oil-barrel" },
    EmptyLubricantBarrel: { "type": "recipe", "name": "empty-lubricant-barrel" },
    EmptySulfuricAcidBarrel: { "type": "recipe", "name": "empty-sulfuric-acid-barrel" },
    EmptyFluoroketoneHotBarrel: { "type": "recipe", "name": "empty-fluoroketone-hot-barrel" },
    EmptyFluoroketoneColdBarrel: { "type": "recipe", "name": "empty-fluoroketone-cold-barrel" },
    IronGearWheel: { 'name': 'iron-gear-wheel' },
    IronStick: { 'name': 'iron-stick' },
    CopperCable: { 'name': 'copper-cable' },
    Barrel: { "name": "barrel" },
    ElectronicCircuit: { 'name': 'electronic-circuit' },
    AdvancedCircuit: { 'name': 'advanced-circuit' },
    ProcessingUnit: { 'name': 'processing-unit' },
    EngineUnit: { 'name': 'engine-unit' },
    ElectricEngineUnit: { 'name': 'electric-engine-unit' },
    FlyingRobotFrame: { 'name': 'flying-robot-frame' },
    LowDensityStructure: { 'name': 'low-density-structure' },
    RocketFuel: { 'name': 'rocket-fuel' },
    RocketPart: { "type": "recipe", "name": "rocket-part" },
    UraniumProcessing: { "type": "recipe", "name": "uranium-processing" },
    Uranium235: { 'name': 'uranium-235' },
    Uranium238: { 'name': 'uranium-238' },
    UraniumFuelCell: { 'name': 'uranium-fuel-cell' },
    DepletedUraniumFuelCell: { "name": "depleted-uranium-fuel-cell" },
    NuclearFuelReprocessing: { "type": "recipe", "name": "nuclear-fuel-reprocessing" },
    KovarexEnrichmentProcess: { "type": "recipe", "name": "kovarex-enrichment-process" },
    NuclearFuel: { 'name': 'nuclear-fuel' },
    Calcite: { "name": "calcite" },
    MoltenIronFromLava: { "type": "recipe", "name": "molten-iron-from-lava" },
    MoltenCopperFromLava: { "type": "recipe", "name": "molten-copper-from-lava" },
    CastingIron: { "type": "recipe", "name": "casting-iron" },
    CastingCopper: { "type": "recipe", "name": "casting-copper" },
    CastingSteel: { "type": "recipe", "name": "casting-steel" },
    CastingIronGearWheel: { "type": "recipe", "name": "casting-iron-gear-wheel" },
    CastingIronStick: { "type": "recipe", "name": "casting-iron-stick" },
    CastingLowDensityStructure: { "type": "recipe", "name": "casting-low-density-structure" },
    ConcreteFromMoltenIron: { "type": "recipe", "name": "concrete-from-molten-iron" },
    CastingCopperCable: { "type": "recipe", "name": "casting-copper-cable" },
    TungstenOre: { "name": "tungsten-ore" },
    TungstenCarbide: { "name": "tungsten-carbide" },
    TungstenPlate: { "name": "tungsten-plate" },
    Scrap: { "name": "scrap" },
    ScrapRecycling: { "type": "recipe", "name": "scrap-recycling" },
    HolmiumOre: { "name": "holmium-ore" },
    HolmiumPlate: { "name": "holmium-plate" },
    Superconductor: { "name": "superconductor" },
    Supercapacitor: { "name": "supercapacitor" },
    YumakoProcessing: { "type": "recipe", "name": "yumako-processing" },
    YumakoSeed: { "name": "yumako-seed" },
    JellynutProcessing: { "type": "recipe", "name": "jellynut-processing" },
    JellynutSeed: { "name": "jellynut-seed" },
    TreeSeed: { "name": "tree-seed" },
    Yumako: { "name": "yumako" },
    Jellynut: { "name": "jellynut" },
    IronBacteria: { "name": "iron-bacteria" },
    CopperBacteria: { "name": "copper-bacteria" },
    NutrientsFromSpoilage: { "type": "recipe", "name": "nutrients-from-spoilage" },
    Spoilage: { "name": "spoilage" },
    NutrientsFromYumakoMash: { "type": "recipe", "name": "nutrients-from-yumako-mash" },
    Nutrients: { "name": "nutrients" },
    NutrientsFromBioflux: { "type": "recipe", "name": "nutrients-from-bioflux" },
    IronBacteriaCultivation: { "type": "recipe", "name": "iron-bacteria-cultivation" },
    CopperBacteriaCultivation: { "type": "recipe", "name": "copper-bacteria-cultivation" },
    Bioflux: { "name": "bioflux" },
    YumakoMash: { "name": "yumako-mash" },
    Jelly: { "name": "jelly" },
    RocketFuelFromJelly: { "type": "recipe", "name": "rocket-fuel-from-jelly" },
    Biolubricant: { "type": "recipe", "name": "biolubricant" },
    Bioplastic: { "type": "recipe", "name": "bioplastic" },
    Biosulfur: { "type": "recipe", "name": "biosulfur" },
    CarbonFiber: { "name": "carbon-fiber" },
    BurntSpoilage: { "type": "recipe", "name": "burnt-spoilage" },
    BiterEgg: { "name": "biter-egg" },
    PentapodEgg: { "name": "pentapod-egg" },
    WoodProcessing: { "type": "recipe", "name": "wood-processing" },
    FishBreeding: { "type": "recipe", "name": "fish-breeding" },
    NutrientsFromFish: { "type": "recipe", "name": "nutrients-from-fish" },
    NutrientsFromBiterEgg: { "type": "recipe", "name": "nutrients-from-biter-egg" },
    AmmoniacalSolutionSeparation: { "type": "recipe", "name": "ammoniacal-solution-separation" },
    SolidFuelFromAmmonia: { "type": "recipe", "name": "solid-fuel-from-ammonia" },
    AmmoniaRocketFuel: { "type": "recipe", "name": "ammonia-rocket-fuel" },
    FluoroketoneCooling: { "type": "recipe", "name": "fluoroketone-cooling" },
    Lithium: { "name": "lithium" },
    LithiumPlate: { "name": "lithium-plate" },
    QuantumProcessor: { "name": "quantum-processor" },
    FusionPowerCell: { "name": "fusion-power-cell" },
    AutomationSciencePack: { 'name': 'automation-science-pack' },
    LogisticSciencePack: { 'name': 'logistic-science-pack' },
    MilitarySciencePack: { 'name': 'military-science-pack' },
    ChemicalSciencePack: { 'name': 'chemical-science-pack' },
    ProductionSciencePack: { 'name': 'production-science-pack' },
    UtilitySciencePack: { 'name': 'utility-science-pack' },
    SpaceSciencePack: { 'name': 'space-science-pack' },
    MetallurgicSciencePack: { "name": "metallurgic-science-pack" },
    ElectromagneticSciencePack: { "name": "electromagnetic-science-pack" },
    AgriculturalSciencePack: { "name": "agricultural-science-pack" },
    CryogenicSciencePack: { "name": "cryogenic-science-pack" },
    PromethiumSciencePack: { "name": "promethium-science-pack" },
    RocketSilo: { 'name': 'rocket-silo' },
    CargoLandingPad: { "name": "cargo-landing-pad" },
    CargoPod: { "type": "entity", "name": "cargo-pod" },
    CargoPodContainer: { "type": "entity", "name": "cargo-pod-container" },
    SpacePlatformFoundation: { "name": "space-platform-foundation" },
    CargoBay: { "name": "cargo-bay" },
    AsteroidCollector: { "name": "asteroid-collector" },
    Crusher: { "name": "crusher" },
    Thruster: { "name": "thruster" },
    SpacePlatformStarterPack: { "name": "space-platform-starter-pack" },
    SmallMetallicAsteroid: { "type": "entity", "name": "small-metallic-asteroid" },
    MediumMetallicAsteroid: { "type": "entity", "name": "medium-metallic-asteroid" },
    BigMetallicAsteroid: { "type": "entity", "name": "big-metallic-asteroid" },
    HugeMetallicAsteroid: { "type": "entity", "name": "huge-metallic-asteroid" },
    SmallCarbonicAsteroid: { "type": "entity", "name": "small-carbonic-asteroid" },
    MediumCarbonicAsteroid: { "type": "entity", "name": "medium-carbonic-asteroid" },
    BigCarbonicAsteroid: { "type": "entity", "name": "big-carbonic-asteroid" },
    HugeCarbonicAsteroid: { "type": "entity", "name": "huge-carbonic-asteroid" },
    SmallOxideAsteroid: { "type": "entity", "name": "small-oxide-asteroid" },
    MediumOxideAsteroid: { "type": "entity", "name": "medium-oxide-asteroid" },
    BigOxideAsteroid: { "type": "entity", "name": "big-oxide-asteroid" },
    HugeOxideAsteroid: { "type": "entity", "name": "huge-oxide-asteroid" },
    SmallPromethiumAsteroid: { "type": "entity", "name": "small-promethium-asteroid" },
    MediumPromethiumAsteroid: { "type": "entity", "name": "medium-promethium-asteroid" },
    BigPromethiumAsteroid: { "type": "entity", "name": "big-promethium-asteroid" },
    HugePromethiumAsteroid: { "type": "entity", "name": "huge-promethium-asteroid" },
    MetallicAsteroidChunk: { "name": "metallic-asteroid-chunk" },
    CarbonicAsteroidChunk: { "name": "carbonic-asteroid-chunk" },
    OxideAsteroidChunk: { "name": "oxide-asteroid-chunk" },
    PromethiumAsteroidChunk: { "name": "promethium-asteroid-chunk" },
    MetallicAsteroidCrushing: { "type": "recipe", "name": "metallic-asteroid-crushing" },
    MetallicAsteroidReprocessing: { "type": "recipe", "name": "metallic-asteroid-reprocessing" },
    CarbonicAsteroidCrushing: { "type": "recipe", "name": "carbonic-asteroid-crushing" },
    CarbonicAsteroidReprocessing: { "type": "recipe", "name": "carbonic-asteroid-reprocessing" },
    OxideAsteroidCrushing: { "type": "recipe", "name": "oxide-asteroid-crushing" },
    OxideAsteroidReprocessing: { "type": "recipe", "name": "oxide-asteroid-reprocessing" },
    AdvancedMetallicAsteroidCrushing: { "type": "recipe", "name": "advanced-metallic-asteroid-crushing" },
    AdvancedCarbonicAsteroidCrushing: { "type": "recipe", "name": "advanced-carbonic-asteroid-crushing" },
    AdvancedOxideAsteroidCrushing: { "type": "recipe", "name": "advanced-oxide-asteroid-crushing" },
    AdvancedThrusterFuel: { "type": "recipe", "name": "advanced-thruster-fuel" },
    AdvancedThrusterOxidizer: { "type": "recipe", "name": "advanced-thruster-oxidizer" },
    Nauvis: { "type": "space-location", "name": "nauvis" },
    Vulcanus: { "type": "space-location", "name": "vulcanus" },
    Gleba: { "type": "space-location", "name": "gleba" },
    Fulgora: { "type": "space-location", "name": "fulgora" },
    Aquilo: { "type": "space-location", "name": "aquilo" },
    SolarSystemEdge: { "type": "space-location", "name": "solar-system-edge" },
    ShatteredPlanet: { "type": "space-location", "name": "shattered-planet" },
    Pistol: { 'name': 'pistol' },
    SubmachineGun: { 'name': 'submachine-gun' },
    Railgun: { "name": "railgun" },
    Teslagun: { "name": "teslagun" },
    Shotgun: { 'name': 'shotgun' },
    CombatShotgun: { 'name': 'combat-shotgun' },
    RocketLauncher: { 'name': 'rocket-launcher' },
    Flamethrower: { 'name': 'flamethrower' },
    FirearmMagazine: { 'name': 'firearm-magazine' },
    PiercingRoundsMagazine: { 'name': 'piercing-rounds-magazine' },
    UraniumRoundsMagazine: { 'name': 'uranium-rounds-magazine' },
    ShotgunShell: { 'name': 'shotgun-shell' },
    PiercingShotgunShell: { 'name': 'piercing-shotgun-shell' },
    CannonShell: { 'name': 'cannon-shell' },
    ExplosiveCannonShell: { 'name': 'explosive-cannon-shell' },
    UraniumCannonShell: { 'name': 'uranium-cannon-shell' },
    ExplosiveUraniumCannonShell: { 'name': 'explosive-uranium-cannon-shell' },
    ArtilleryShell: { 'name': 'artillery-shell' },
    Rocket: { 'name': 'rocket' },
    ExplosiveRocket: { 'name': 'explosive-rocket' },
    AtomicBomb: { 'name': 'atomic-bomb' },
    CaptureRobotRocket: { "name": "capture-robot-rocket" },
    FlamethrowerAmmo: { 'name': 'flamethrower-ammo' },
    RailgunAmmo: { "name": "railgun-ammo" },
    TeslaAmmo: { "name": "tesla-ammo" },
    Grenade: { 'name': 'grenade' },
    ClusterGrenade: { 'name': 'cluster-grenade' },
    PoisonCapsule: { 'name': 'poison-capsule' },
    SlowdownCapsule: { 'name': 'slowdown-capsule' },
    DefenderCapsule: { 'name': 'defender-capsule' },
    Defender: { "type": "entity", "name": "defender" },
    DistractorCapsule: { 'name': 'distractor-capsule' },
    Distractor: { "type": "entity", "name": "distractor" },
    DestroyerCapsule: { 'name': 'destroyer-capsule' },
    Destroyer: { "type": "entity", "name": "destroyer" },
    LightArmor: { 'name': 'light-armor' },
    HeavyArmor: { 'name': 'heavy-armor' },
    ModularArmor: { 'name': 'modular-armor' },
    PowerArmor: { 'name': 'power-armor' },
    PowerArmorMk2: { 'name': 'power-armor-mk2' },
    MechArmor: { "name": "mech-armor" },
    SolarPanelEquipment: { 'name': 'solar-panel-equipment' },
    FissionReactorEquipment: { "name": "fission-reactor-equipment" },
    FusionReactorEquipment: { 'name': 'fusion-reactor-equipment' },
    BatteryEquipment: { 'name': 'battery-equipment' },
    BatteryMk2Equipment: { 'name': 'battery-mk2-equipment' },
    BatteryMk3Equipment: { "name": "battery-mk3-equipment" },
    BeltImmunityEquipment: { 'name': 'belt-immunity-equipment' },
    ExoskeletonEquipment: { 'name': 'exoskeleton-equipment' },
    PersonalRoboportEquipment: { 'name': 'personal-roboport-equipment' },
    PersonalRoboportMk2Equipment: { 'name': 'personal-roboport-mk2-equipment' },
    NightVisionEquipment: { 'name': 'night-vision-equipment' },
    ToolbeltEquipment: { "name": "toolbelt-equipment" },
    EnergyShieldEquipment: { 'name': 'energy-shield-equipment' },
    EnergyShieldMk2Equipment: { 'name': 'energy-shield-mk2-equipment' },
    PersonalLaserDefenseEquipment: { 'name': 'personal-laser-defense-equipment' },
    DischargeDefenseEquipment: { 'name': 'discharge-defense-equipment' },
    StoneWall: { 'name': 'stone-wall' },
    Gate: { 'name': 'gate' },
    Radar: { 'name': 'radar' },
    LandMine: { 'name': 'land-mine' },
    GunTurret: { 'name': 'gun-turret' },
    LaserTurret: { 'name': 'laser-turret' },
    FlamethrowerTurret: { 'name': 'flamethrower-turret' },
    ArtilleryTurret: { 'name': 'artillery-turret' },
    RocketTurret: { "name": "rocket-turret" },
    TeslaTurret: { "name": "tesla-turret" },
    RailgunTurret: { "name": "railgun-turret" },
    Water: { 'type': 'fluid', 'name': 'water' },
    Steam: { 'type': 'fluid', 'name': 'steam' },
    CrudeOil: { 'type': 'fluid', 'name': 'crude-oil' },
    PetroleumGas: { 'type': 'fluid', 'name': 'petroleum-gas' },
    LightOil: { 'type': 'fluid', 'name': 'light-oil' },
    HeavyOil: { 'type': 'fluid', 'name': 'heavy-oil' },
    Lubricant: { 'type': 'fluid', 'name': 'lubricant' },
    SulfuricAcid: { 'type': 'fluid', 'name': 'sulfuric-acid' },
    ThrusterFuel: { "type": "fluid", "name": "thruster-fuel" },
    ThrusterOxidizer: { "type": "fluid", "name": "thruster-oxidizer" },
    Lava: { "type": "fluid", "name": "lava" },
    MoltenIron: { "type": "fluid", "name": "molten-iron" },
    MoltenCopper: { "type": "fluid", "name": "molten-copper" },
    HolmiumSolution: { "type": "fluid", "name": "holmium-solution" },
    Electrolyte: { "type": "fluid", "name": "electrolyte" },
    AmmoniacalSolution: { "type": "fluid", "name": "ammoniacal-solution" },
    Ammonia: { "type": "fluid", "name": "ammonia" },
    Fluorine: { "type": "fluid", "name": "fluorine" },
    FluoroketoneHot: { "type": "fluid", "name": "fluoroketone-hot" },
    FluoroketoneCold: { "type": "fluid", "name": "fluoroketone-cold" },
    LithiumBrine: { "type": "fluid", "name": "lithium-brine" },
    FusionPlasma: { "type": "fluid", "name": "fusion-plasma" },
    Signal0: { 'type': 'virtual', 'name': 'signal-0' },
    Signal1: { 'type': 'virtual', 'name': 'signal-1' },
    Signal2: { 'type': 'virtual', 'name': 'signal-2' },
    Signal3: { 'type': 'virtual', 'name': 'signal-3' },
    Signal4: { 'type': 'virtual', 'name': 'signal-4' },
    Signal5: { 'type': 'virtual', 'name': 'signal-5' },
    Signal6: { 'type': 'virtual', 'name': 'signal-6' },
    Signal7: { 'type': 'virtual', 'name': 'signal-7' },
    Signal8: { 'type': 'virtual', 'name': 'signal-8' },
    Signal9: { 'type': 'virtual', 'name': 'signal-9' },
    SignalA: { 'type': 'virtual', 'name': 'signal-A' },
    SignalB: { 'type': 'virtual', 'name': 'signal-B' },
    SignalC: { 'type': 'virtual', 'name': 'signal-C' },
    SignalD: { 'type': 'virtual', 'name': 'signal-D' },
    SignalE: { 'type': 'virtual', 'name': 'signal-E' },
    SignalF: { 'type': 'virtual', 'name': 'signal-F' },
    SignalG: { 'type': 'virtual', 'name': 'signal-G' },
    SignalH: { 'type': 'virtual', 'name': 'signal-H' },
    SignalI: { 'type': 'virtual', 'name': 'signal-I' },
    SignalJ: { 'type': 'virtual', 'name': 'signal-J' },
    SignalK: { 'type': 'virtual', 'name': 'signal-K' },
    SignalL: { 'type': 'virtual', 'name': 'signal-L' },
    SignalM: { 'type': 'virtual', 'name': 'signal-M' },
    SignalN: { 'type': 'virtual', 'name': 'signal-N' },
    SignalO: { 'type': 'virtual', 'name': 'signal-O' },
    SignalP: { 'type': 'virtual', 'name': 'signal-P' },
    SignalQ: { 'type': 'virtual', 'name': 'signal-Q' },
    SignalR: { 'type': 'virtual', 'name': 'signal-R' },
    SignalS: { 'type': 'virtual', 'name': 'signal-S' },
    SignalT: { 'type': 'virtual', 'name': 'signal-T' },
    SignalU: { 'type': 'virtual', 'name': 'signal-U' },
    SignalV: { 'type': 'virtual', 'name': 'signal-V' },
    SignalW: { 'type': 'virtual', 'name': 'signal-W' },
    SignalX: { 'type': 'virtual', 'name': 'signal-X' },
    SignalY: { 'type': 'virtual', 'name': 'signal-Y' },
    SignalZ: { 'type': 'virtual', 'name': 'signal-Z' },
    SignalRed: { 'type': 'virtual', 'name': 'signal-red' },
    SignalGreen: { 'type': 'virtual', 'name': 'signal-green' },
    SignalBlue: { 'type': 'virtual', 'name': 'signal-blue' },
    SignalYellow: { 'type': 'virtual', 'name': 'signal-yellow' },
    SignalPink: { 'type': 'virtual', 'name': 'signal-pink' },
    SignalCyan: { 'type': 'virtual', 'name': 'signal-cyan' },
    SignalWhite: { 'type': 'virtual', 'name': 'signal-white' },
    SignalGrey: { 'type': 'virtual', 'name': 'signal-grey' },
    SignalBlack: { 'type': 'virtual', 'name': 'signal-black' },
    SignalCheck: { 'type': 'virtual', 'name': 'signal-check' },
    SignalDeny: { "type": "virtual", "name": "signal-deny" },
    SignalInfo: { 'type': 'virtual', 'name': 'signal-info' },
    SignalDot: { 'type': 'virtual', 'name': 'signal-dot' },
    ShapeVertical: { "type": "virtual", "name": "shape-vertical" },
    ShapeHorizontal: { "type": "virtual", "name": "shape-horizontal" },
    ShapeDiagonal: { "type": "virtual", "name": "shape-diagonal" },
    ShapeCurve: { "type": "virtual", "name": "shape-curve" },
    ShapeCross: { "type": "virtual", "name": "shape-cross" },
    ShapeDiagonalCross: { "type": "virtual", "name": "shape-diagonal-cross" },
    ShapeCorner: { "type": "virtual", "name": "shape-corner" },
    ShapeT: { "type": "virtual", "name": "shape-t" },
    ShapeCircle: { "type": "virtual", "name": "shape-circle" },
    UpArrow: { "type": "virtual", "name": "up-arrow" },
    UpRightArrow: { "type": "virtual", "name": "up-right-arrow" },
    RightArrow: { "type": "virtual", "name": "right-arrow" },
    DownRightArrow: { "type": "virtual", "name": "down-right-arrow" },
    DownArrow: { "type": "virtual", "name": "down-arrow" },
    DownLeftArrow: { "type": "virtual", "name": "down-left-arrow" },
    LeftArrow: { "type": "virtual", "name": "left-arrow" },
    UpLeftArrow: { "type": "virtual", "name": "up-left-arrow" },
    SignalStackSize: { "type": "virtual", "name": "signal-stack-size" },
    SignalHeart: { "type": "virtual", "name": "signal-heart" },
    SignalSkull: { "type": "virtual", "name": "signal-skull" },
    SignalGhost: { "type": "virtual", "name": "signal-ghost" },
    SignalAnything: { 'type': 'virtual', 'name': 'signal-anything' },
    SignalEach: { 'type': 'virtual', 'name': 'signal-each' },
    SignalEverything: { 'type': 'virtual', 'name': 'signal-everything' },
    SmallBiter: { "type": "entity", "name": "small-biter" },
    MediumBiter: { "type": "entity", "name": "medium-biter" },
    BigBiter: { "type": "entity", "name": "big-biter" },
    BehemothBiter: { "type": "entity", "name": "behemoth-biter" },
    SmallSpitter: { "type": "entity", "name": "small-spitter" },
    MediumSpitter: { "type": "entity", "name": "medium-spitter" },
    BigSpitter: { "type": "entity", "name": "big-spitter" },
    BehemothSpitter: { "type": "entity", "name": "behemoth-spitter" },
    SmallWormTurret: { "type": "entity", "name": "small-worm-turret" },
    MediumWormTurret: { "type": "entity", "name": "medium-worm-turret" },
    BigWormTurret: { "type": "entity", "name": "big-worm-turret" },
    BehemothWormTurret: { "type": "entity", "name": "behemoth-worm-turret" },
    BiterSpawner: { "type": "entity", "name": "biter-spawner" },
    SpitterSpawner: { "type": "entity", "name": "spitter-spawner" },
    SmallWrigglerPentapod: { "type": "entity", "name": "small-wriggler-pentapod" },
    SmallWrigglerPentapodPremature: { "type": "entity", "name": "small-wriggler-pentapod-premature" },
    MediumWrigglerPentapod: { "type": "entity", "name": "medium-wriggler-pentapod" },
    MediumWrigglerPentapodPremature: { "type": "entity", "name": "medium-wriggler-pentapod-premature" },
    BigWrigglerPentapod: { "type": "entity", "name": "big-wriggler-pentapod" },
    BigWrigglerPentapodPremature: { "type": "entity", "name": "big-wriggler-pentapod-premature" },
    SmallStraferPentapod: { "type": "entity", "name": "small-strafer-pentapod" },
    MediumStraferPentapod: { "type": "entity", "name": "medium-strafer-pentapod" },
    BigStraferPentapod: { "type": "entity", "name": "big-strafer-pentapod" },
    SmallStomperPentapod: { "type": "entity", "name": "small-stomper-pentapod" },
    MediumStomperPentapod: { "type": "entity", "name": "medium-stomper-pentapod" },
    BigStomperPentapod: { "type": "entity", "name": "big-stomper-pentapod" },
    GlebaSpawner: { "type": "entity", "name": "gleba-spawner" },
    GlebaSpawnerSmall: { "type": "entity", "name": "gleba-spawner-small" },
    SmallDemolisher: { "type": "entity", "name": "small-demolisher" },
    MediumDemolisher: { "type": "entity", "name": "medium-demolisher" },
    BigDemolisher: { "type": "entity", "name": "big-demolisher" },
    Cliff: { "type": "entity", "name": "cliff" },
    CliffFulgora: { "type": "entity", "name": "cliff-fulgora" },
    CliffGleba: { "type": "entity", "name": "cliff-gleba" },
    CliffVulcanus: { "type": "entity", "name": "cliff-vulcanus" },
    CraterCliff: { "type": "entity", "name": "crater-cliff" },
    Character: { "type": "entity", "name": "character" },
    Slipstack: { "type": "entity", "name": "slipstack" },
    Funneltrunk: { "type": "entity", "name": "funneltrunk" },
    Hairyclubnub: { "type": "entity", "name": "hairyclubnub" },
    Teflilly: { "type": "entity", "name": "teflilly" },
    Stingfrond: { "type": "entity", "name": "stingfrond" },
    Boompuff: { "type": "entity", "name": "boompuff" },
    Cuttlepop: { "type": "entity", "name": "cuttlepop" },
    BigSandRock: { "type": "entity", "name": "big-sand-rock" },
    CopperStromatolite: { "type": "entity", "name": "copper-stromatolite" },
    IronStromatolite: { "type": "entity", "name": "iron-stromatolite" },
    HugeRock: { "type": "entity", "name": "huge-rock" },
    BigStomperShell: { "type": "entity", "name": "big-stomper-shell" },
    BigVolcanicRock: { "type": "entity", "name": "big-volcanic-rock" },
    MediumStomperShell: { "type": "entity", "name": "medium-stomper-shell" },
    SmallStomperShell: { "type": "entity", "name": "small-stomper-shell" },
    HugeVolcanicRock: { "type": "entity", "name": "huge-volcanic-rock" },
    VulcanusChimneyShort: { "type": "entity", "name": "vulcanus-chimney-short" },
    VulcanusChimneyTruncated: { "type": "entity", "name": "vulcanus-chimney-truncated" },
    VulcanusChimney: { "type": "entity", "name": "vulcanus-chimney" },
    VulcanusChimneyCold: { "type": "entity", "name": "vulcanus-chimney-cold" },
    VulcanusChimneyFaded: { "type": "entity", "name": "vulcanus-chimney-faded" },
    Fulgurite: { "type": "entity", "name": "fulgurite" },
    FulguriteSmall: { "type": "entity", "name": "fulgurite-small" },
    BigFulgoraRock: { "type": "entity", "name": "big-fulgora-rock" },
    FulgoranRuinSmall: { "type": "entity", "name": "fulgoran-ruin-small" },
    FulgoranRuinMedium: { "type": "entity", "name": "fulgoran-ruin-medium" },
    FulgoranRuinStonehenge: { "type": "entity", "name": "fulgoran-ruin-stonehenge" },
    FulgoranRuinBig: { "type": "entity", "name": "fulgoran-ruin-big" },
    FulgoranRuinColossal: { "type": "entity", "name": "fulgoran-ruin-colossal" },
    FulgoranRuinHuge: { "type": "entity", "name": "fulgoran-ruin-huge" },
    FulgoranRuinVault: { "type": "entity", "name": "fulgoran-ruin-vault" },
    FulgoranRuinAttractor: { "type": "entity", "name": "fulgoran-ruin-attractor" },
    LithiumIcebergBig: { "type": "entity", "name": "lithium-iceberg-big" },
    LithiumIcebergHuge: { "type": "entity", "name": "lithium-iceberg-huge" },
    SmallDemolisherCorpse: { "type": "entity", "name": "small-demolisher-corpse" },
    MediumDemolisherCorpse: { "type": "entity", "name": "medium-demolisher-corpse" },
    BigDemolisherCorpse: { "type": "entity", "name": "big-demolisher-corpse" },
    CrudeOilDeposit: { "type": "entity", "name": "crude-oil" },
    LithiumBrineDeposit: { "type": "entity", "name": "lithium-brine" },
    SulfuricAcidGeyser: { "type": "entity", "name": "sulfuric-acid-geyser" },
    FluorineVent: { "type": "entity", "name": "fluorine-vent" },
    Lightning: { "type": "entity", "name": "lightning" },
    Normal: { "type": "quality", "name": "normal" },
    Uncommon: { "type": "quality", "name": "uncommon" },
    Rare: { "type": "quality", "name": "rare" },
    Epic: { "type": "quality", "name": "epic" },
    Legendary: { "type": "quality", "name": "legendary" },
    SignalAnyQuality: { "type": "virtual", "name": "signal-any-quality" },
    CopperWire: { "name": "copper-wire" },
    GreenWire: { "name": "green-wire" },
    RedWire: { "name": "red-wire" },
    SpidertronRemote: { "name": "spidertron-remote" },
    DischargeDefenseRemote: { "name": "discharge-defense-remote" },
    ArtilleryTargetingRemote: { "name": "artillery-targeting-remote" },
    EntityGhost: { "type": "entity", "name": "entity-ghost" },
    ItemOnGround: { "type": "entity", "name": "item-on-ground" },
    ItemRequestProxy: { "type": "entity", "name": "item-request-proxy" },
    TileGhost: { "type": "entity", "name": "tile-ghost" },
    WubeLogoSpacePlatform: { "type": "entity", "name": "wube-logo-space-platform" },
}

export const UsableSignals: Signal[] = [
    Signals.WoodenChest,
    Signals.IronChest,
    Signals.SteelChest,
    Signals.StorageTank,
    Signals.TransportBelt,
    Signals.FastTransportBelt,
    Signals.ExpressTransportBelt,
    Signals.TurboTransportBelt,
    Signals.UndergroundBelt,
    Signals.FastUndergroundBelt,
    Signals.ExpressUndergroundBelt,
    Signals.TurboUndergroundBelt,
    Signals.Splitter,
    Signals.FastSplitter,
    Signals.ExpressSplitter,
    Signals.TurboSplitter,
    Signals.BurnerInserter,
    Signals.Inserter,
    Signals.LongHandedInserter,
    Signals.FastInserter,
    Signals.BulkInserter,
    Signals.StackInserter,
    Signals.SmallElectricPole,
    Signals.MediumElectricPole,
    Signals.BigElectricPole,
    Signals.Substation,
    Signals.Pipe,
    Signals.PipeToGround,
    Signals.CastingPipe,
    Signals.CastingPipeToGround,
    Signals.Pump,
    Signals.Rail,
    Signals.RailRamp,
    Signals.RailSupport,
    Signals.TrainStop,
    Signals.RailSignal,
    Signals.RailChainSignal,
    Signals.Locomotive,
    Signals.CargoWagon,
    Signals.FluidWagon,
    Signals.ArtilleryWagon,
    Signals.Car,
    Signals.Tank,
    Signals.Spidertron,
    Signals.LogisticRobot,
    Signals.ConstructionRobot,
    Signals.ActiveProviderChest,
    Signals.PassiveProviderChest,
    Signals.StorageChest,
    Signals.BufferChest,
    Signals.RequesterChest,
    Signals.Roboport,
    Signals.SmallLamp,
    Signals.ArithmeticCombinator,
    Signals.DeciderCombinator,
    Signals.SelectorCombinator,
    Signals.ConstantCombinator,
    Signals.PowerSwitch,
    Signals.ProgrammableSpeaker,
    Signals.DisplayPanel,
    Signals.StoneBrick,
    Signals.Concrete,
    Signals.HazardConcrete,
    Signals.RefinedConcrete,
    Signals.RefinedHazardConcrete,
    Signals.Landfill,
    Signals.ArtificialYumakoSoil,
    Signals.OvergrowthYumakoSoil,
    Signals.ArtificialJellynutSoil,
    Signals.OvergrowthJellynutSoil,
    Signals.IcePlatform,
    Signals.Foundation,
    Signals.CliffExplosives,
    Signals.RepairPack,
    Signals.Blueprint,
    Signals.DeconstructionPlanner,
    Signals.UpgradePlanner,
    Signals.BlueprintBook,
    Signals.Boiler,
    Signals.SteamEngine,
    Signals.SolarPanel,
    Signals.Accumulator,
    Signals.NuclearReactor,
    Signals.HeatPipe,
    Signals.HeatExchanger,
    Signals.SteamTurbine,
    Signals.FusionReactor,
    Signals.FusionGenerator,
    Signals.BurnerMiningDrill,
    Signals.ElectricMiningDrill,
    Signals.BigMiningDrill,
    Signals.OffshorePump,
    Signals.Pumpjack,
    Signals.StoneFurnace,
    Signals.SteelFurnace,
    Signals.ElectricFurnace,
    Signals.Foundry,
    Signals.Recycler,
    Signals.AgriculturalTower,
    Signals.Biochamber,
    Signals.CaptiveBiterSpawner,
    Signals.AssemblingMachine1,
    Signals.AssemblingMachine2,
    Signals.AssemblingMachine3,
    Signals.OilRefinery,
    Signals.ChemicalPlant,
    Signals.Centrifuge,
    Signals.ElectromagneticPlant,
    Signals.CryogenicPlant,
    Signals.Lab,
    Signals.Biolab,
    Signals.LightningRod,
    Signals.LightningCollector,
    Signals.HeatingTower,
    Signals.Beacon,
    Signals.SpeedModule,
    Signals.SpeedModule2,
    Signals.SpeedModule3,
    Signals.EfficiencyModule,
    Signals.EfficiencyModule2,
    Signals.EfficiencyModule3,
    Signals.ProductivityModule,
    Signals.ProductivityModule2,
    Signals.ProductivityModule3,
    Signals.QualityModule,
    Signals.QualityModule2,
    Signals.QualityModule3,
    Signals.BasicOilProcessing,
    Signals.AdvancedOilProcessing,
    Signals.SimpleCoalLiquefaction,
    Signals.CoalLiquefaction,
    Signals.HeavyOilCracking,
    Signals.LightOilCracking,
    Signals.SolidFuelFromPetroleumGas,
    Signals.SolidFuelFromLightOil,
    Signals.SolidFuelFromHeavyOil,
    Signals.AcidNeutralisation,
    Signals.SteamCondensation,
    Signals.IceMelting,
    Signals.Wood,
    Signals.Coal,
    Signals.Stone,
    Signals.IronOre,
    Signals.CopperOre,
    Signals.UraniumOre,
    Signals.RawFish,
    Signals.Ice,
    Signals.IronPlate,
    Signals.CopperPlate,
    Signals.SteelPlate,
    Signals.SolidFuel,
    Signals.PlasticBar,
    Signals.Sulfur,
    Signals.Battery,
    Signals.Explosives,
    Signals.Carbon,
    Signals.CoalSynthesis,
    Signals.WaterBarrel,
    Signals.CrudeOilBarrel,
    Signals.PetroleumGasBarrel,
    Signals.LightOilBarrel,
    Signals.HeavyOilBarrel,
    Signals.LubricantBarrel,
    Signals.SulfuricAcidBarrel,
    Signals.FluoroketoneHotBarrel,
    Signals.FluoroketoneColdBarrel,
    Signals.FillWaterBarrel,
    Signals.FillCrudeOilBarrel,
    Signals.FillPetroleumGasBarrel,
    Signals.FillLightOilBarrel,
    Signals.FillHeavyOilBarrel,
    Signals.FillLubricantBarrel,
    Signals.FillSulfuricAcidBarrel,
    Signals.FillFluoroketoneHotBarrel,
    Signals.FillFluoroketoneColdBarrel,
    Signals.EmptyWaterBarrel,
    Signals.EmptyCrudeOilBarrel,
    Signals.EmptyPetroleumGasBarrel,
    Signals.EmptyLightOilBarrel,
    Signals.EmptyHeavyOilBarrel,
    Signals.EmptyLubricantBarrel,
    Signals.EmptySulfuricAcidBarrel,
    Signals.EmptyFluoroketoneHotBarrel,
    Signals.EmptyFluoroketoneColdBarrel,
    Signals.IronGearWheel,
    Signals.IronStick,
    Signals.CopperCable,
    Signals.Barrel,
    Signals.ElectronicCircuit,
    Signals.AdvancedCircuit,
    Signals.ProcessingUnit,
    Signals.EngineUnit,
    Signals.ElectricEngineUnit,
    Signals.FlyingRobotFrame,
    Signals.LowDensityStructure,
    Signals.RocketFuel,
    Signals.RocketPart,
    Signals.UraniumProcessing,
    Signals.Uranium235,
    Signals.Uranium238,
    Signals.UraniumFuelCell,
    Signals.DepletedUraniumFuelCell,
    Signals.NuclearFuelReprocessing,
    Signals.KovarexEnrichmentProcess,
    Signals.NuclearFuel,
    Signals.Calcite,
    Signals.MoltenIronFromLava,
    Signals.MoltenCopperFromLava,
    Signals.CastingIron,
    Signals.CastingCopper,
    Signals.CastingSteel,
    Signals.CastingIronGearWheel,
    Signals.CastingIronStick,
    Signals.CastingLowDensityStructure,
    Signals.ConcreteFromMoltenIron,
    Signals.CastingCopperCable,
    Signals.TungstenOre,
    Signals.TungstenCarbide,
    Signals.TungstenPlate,
    Signals.Scrap,
    Signals.ScrapRecycling,
    Signals.HolmiumOre,
    Signals.HolmiumPlate,
    Signals.Superconductor,
    Signals.Supercapacitor,
    Signals.YumakoProcessing,
    Signals.YumakoSeed,
    Signals.JellynutProcessing,
    Signals.JellynutSeed,
    Signals.TreeSeed,
    Signals.Yumako,
    Signals.Jellynut,
    Signals.IronBacteria,
    Signals.CopperBacteria,
    Signals.NutrientsFromSpoilage,
    Signals.Spoilage,
    Signals.NutrientsFromYumakoMash,
    Signals.Nutrients,
    Signals.NutrientsFromBioflux,
    Signals.IronBacteriaCultivation,
    Signals.CopperBacteriaCultivation,
    Signals.Bioflux,
    Signals.YumakoMash,
    Signals.Jelly,
    Signals.RocketFuelFromJelly,
    Signals.Biolubricant,
    Signals.Bioplastic,
    Signals.Biosulfur,
    Signals.CarbonFiber,
    Signals.BurntSpoilage,
    Signals.BiterEgg,
    Signals.PentapodEgg,
    Signals.WoodProcessing,
    Signals.FishBreeding,
    Signals.NutrientsFromFish,
    Signals.NutrientsFromBiterEgg,
    Signals.AmmoniacalSolutionSeparation,
    Signals.SolidFuelFromAmmonia,
    Signals.AmmoniaRocketFuel,
    Signals.FluoroketoneCooling,
    Signals.Lithium,
    Signals.LithiumPlate,
    Signals.QuantumProcessor,
    Signals.FusionPowerCell,
    Signals.AutomationSciencePack,
    Signals.LogisticSciencePack,
    Signals.MilitarySciencePack,
    Signals.ChemicalSciencePack,
    Signals.ProductionSciencePack,
    Signals.UtilitySciencePack,
    Signals.SpaceSciencePack,
    Signals.MetallurgicSciencePack,
    Signals.ElectromagneticSciencePack,
    Signals.AgriculturalSciencePack,
    Signals.CryogenicSciencePack,
    Signals.PromethiumSciencePack,
    Signals.RocketSilo,
    Signals.CargoLandingPad,
    Signals.CargoPod,
    Signals.CargoPodContainer,
    Signals.SpacePlatformFoundation,
    Signals.CargoBay,
    Signals.AsteroidCollector,
    Signals.Crusher,
    Signals.Thruster,
    Signals.SpacePlatformStarterPack,
    Signals.SmallMetallicAsteroid,
    Signals.MediumMetallicAsteroid,
    Signals.BigMetallicAsteroid,
    Signals.HugeMetallicAsteroid,
    Signals.SmallCarbonicAsteroid,
    Signals.MediumCarbonicAsteroid,
    Signals.BigCarbonicAsteroid,
    Signals.HugeCarbonicAsteroid,
    Signals.SmallOxideAsteroid,
    Signals.MediumOxideAsteroid,
    Signals.BigOxideAsteroid,
    Signals.HugeOxideAsteroid,
    Signals.SmallPromethiumAsteroid,
    Signals.MediumPromethiumAsteroid,
    Signals.BigPromethiumAsteroid,
    Signals.HugePromethiumAsteroid,
    Signals.MetallicAsteroidChunk,
    Signals.CarbonicAsteroidChunk,
    Signals.OxideAsteroidChunk,
    Signals.PromethiumAsteroidChunk,
    Signals.MetallicAsteroidCrushing,
    Signals.MetallicAsteroidReprocessing,
    Signals.CarbonicAsteroidCrushing,
    Signals.CarbonicAsteroidReprocessing,
    Signals.OxideAsteroidCrushing,
    Signals.OxideAsteroidReprocessing,
    Signals.AdvancedMetallicAsteroidCrushing,
    Signals.AdvancedCarbonicAsteroidCrushing,
    Signals.AdvancedOxideAsteroidCrushing,
    Signals.AdvancedThrusterFuel,
    Signals.AdvancedThrusterOxidizer,
    Signals.Nauvis,
    Signals.Vulcanus,
    Signals.Gleba,
    Signals.Fulgora,
    Signals.Aquilo,
    Signals.SolarSystemEdge,
    Signals.ShatteredPlanet,
    Signals.Pistol,
    Signals.SubmachineGun,
    Signals.Railgun,
    Signals.Teslagun,
    Signals.Shotgun,
    Signals.CombatShotgun,
    Signals.RocketLauncher,
    Signals.Flamethrower,
    Signals.FirearmMagazine,
    Signals.PiercingRoundsMagazine,
    Signals.UraniumRoundsMagazine,
    Signals.ShotgunShell,
    Signals.PiercingShotgunShell,
    Signals.CannonShell,
    Signals.ExplosiveCannonShell,
    Signals.UraniumCannonShell,
    Signals.ExplosiveUraniumCannonShell,
    Signals.ArtilleryShell,
    Signals.Rocket,
    Signals.ExplosiveRocket,
    Signals.AtomicBomb,
    Signals.CaptureRobotRocket,
    Signals.FlamethrowerAmmo,
    Signals.RailgunAmmo,
    Signals.TeslaAmmo,
    Signals.Grenade,
    Signals.ClusterGrenade,
    Signals.PoisonCapsule,
    Signals.SlowdownCapsule,
    Signals.DefenderCapsule,
    Signals.Defender,
    Signals.DistractorCapsule,
    Signals.Distractor,
    Signals.DestroyerCapsule,
    Signals.Destroyer,
    Signals.LightArmor,
    Signals.HeavyArmor,
    Signals.ModularArmor,
    Signals.PowerArmor,
    Signals.PowerArmorMk2,
    Signals.MechArmor,
    Signals.SolarPanelEquipment,
    Signals.FissionReactorEquipment,
    Signals.FusionReactorEquipment,
    Signals.BatteryEquipment,
    Signals.BatteryMk2Equipment,
    Signals.BatteryMk3Equipment,
    Signals.BeltImmunityEquipment,
    Signals.ExoskeletonEquipment,
    Signals.PersonalRoboportEquipment,
    Signals.PersonalRoboportMk2Equipment,
    Signals.NightVisionEquipment,
    Signals.ToolbeltEquipment,
    Signals.EnergyShieldEquipment,
    Signals.EnergyShieldMk2Equipment,
    Signals.PersonalLaserDefenseEquipment,
    Signals.DischargeDefenseEquipment,
    Signals.StoneWall,
    Signals.Gate,
    Signals.Radar,
    Signals.LandMine,
    Signals.GunTurret,
    Signals.LaserTurret,
    Signals.FlamethrowerTurret,
    Signals.ArtilleryTurret,
    Signals.RocketTurret,
    Signals.TeslaTurret,
    Signals.RailgunTurret,
    Signals.Water,
    Signals.Steam,
    Signals.CrudeOil,
    Signals.PetroleumGas,
    Signals.LightOil,
    Signals.HeavyOil,
    Signals.Lubricant,
    Signals.SulfuricAcid,
    Signals.ThrusterFuel,
    Signals.ThrusterOxidizer,
    Signals.Lava,
    Signals.MoltenIron,
    Signals.MoltenCopper,
    Signals.HolmiumSolution,
    Signals.Electrolyte,
    Signals.AmmoniacalSolution,
    Signals.Ammonia,
    Signals.Fluorine,
    Signals.FluoroketoneHot,
    Signals.FluoroketoneCold,
    Signals.LithiumBrine,
    Signals.FusionPlasma,
    Signals.Signal0,
    Signals.Signal1,
    Signals.Signal2,
    Signals.Signal3,
    Signals.Signal4,
    Signals.Signal5,
    Signals.Signal6,
    Signals.Signal7,
    Signals.Signal8,
    Signals.Signal9,
    Signals.SignalA,
    Signals.SignalB,
    Signals.SignalC,
    Signals.SignalD,
    Signals.SignalE,
    Signals.SignalF,
    Signals.SignalG,
    Signals.SignalH,
    Signals.SignalI,
    Signals.SignalJ,
    Signals.SignalK,
    Signals.SignalL,
    Signals.SignalM,
    Signals.SignalN,
    Signals.SignalO,
    Signals.SignalP,
    Signals.SignalQ,
    Signals.SignalR,
    Signals.SignalS,
    Signals.SignalT,
    Signals.SignalU,
    Signals.SignalV,
    Signals.SignalW,
    Signals.SignalX,
    Signals.SignalY,
    Signals.SignalZ,
    Signals.SignalRed,
    Signals.SignalGreen,
    Signals.SignalBlue,
    Signals.SignalYellow,
    Signals.SignalPink,
    Signals.SignalCyan,
    Signals.SignalWhite,
    Signals.SignalGrey,
    Signals.SignalBlack,
    Signals.ShapeVertical,
    Signals.ShapeHorizontal,
    Signals.ShapeDiagonal,
    Signals.ShapeCurve,
    Signals.ShapeCross,
    Signals.ShapeDiagonalCross,
    Signals.ShapeCorner,
    Signals.ShapeT,
    Signals.ShapeCircle,
    Signals.UpArrow,
    Signals.UpRightArrow,
    Signals.RightArrow,
    Signals.DownRightArrow,
    Signals.DownArrow,
    Signals.DownLeftArrow,
    Signals.LeftArrow,
    Signals.UpLeftArrow,
    Signals.SignalStackSize,
    Signals.SignalHeart,
    Signals.SignalSkull,
    Signals.SignalGhost,
    Signals.SmallBiter,
    Signals.MediumBiter,
    Signals.BigBiter,
    Signals.BehemothBiter,
    Signals.SmallSpitter,
    Signals.MediumSpitter,
    Signals.BigSpitter,
    Signals.BehemothSpitter,
    Signals.SmallWormTurret,
    Signals.MediumWormTurret,
    Signals.BigWormTurret,
    Signals.BehemothWormTurret,
    Signals.BiterSpawner,
    Signals.SpitterSpawner,
    Signals.SmallWrigglerPentapod,
    Signals.SmallWrigglerPentapodPremature,
    Signals.MediumWrigglerPentapod,
    Signals.MediumWrigglerPentapodPremature,
    Signals.BigWrigglerPentapod,
    Signals.BigWrigglerPentapodPremature,
    Signals.SmallStraferPentapod,
    Signals.MediumStraferPentapod,
    Signals.BigStraferPentapod,
    Signals.SmallStomperPentapod,
    Signals.MediumStomperPentapod,
    Signals.BigStomperPentapod,
    Signals.GlebaSpawner,
    Signals.GlebaSpawnerSmall,
    Signals.SmallDemolisher,
    Signals.MediumDemolisher,
    Signals.BigDemolisher,
    Signals.Cliff,
    Signals.CliffFulgora,
    Signals.CliffGleba,
    Signals.CliffVulcanus,
    Signals.CraterCliff,
    Signals.Character,
    Signals.Slipstack,
    Signals.Funneltrunk,
    Signals.Hairyclubnub,
    Signals.Teflilly,
    Signals.Stingfrond,
    Signals.Boompuff,
    Signals.Cuttlepop,
    Signals.BigSandRock,
    Signals.CopperStromatolite,
    Signals.IronStromatolite,
    Signals.HugeRock,
    Signals.BigStomperShell,
    Signals.BigVolcanicRock,
    Signals.MediumStomperShell,
    Signals.SmallStomperShell,
    Signals.HugeVolcanicRock,
    Signals.VulcanusChimneyShort,
    Signals.VulcanusChimneyTruncated,
    Signals.VulcanusChimney,
    Signals.VulcanusChimneyCold,
    Signals.VulcanusChimneyFaded,
    Signals.Fulgurite,
    Signals.FulguriteSmall,
    Signals.BigFulgoraRock,
    Signals.FulgoranRuinSmall,
    Signals.FulgoranRuinMedium,
    Signals.FulgoranRuinStonehenge,
    Signals.FulgoranRuinBig,
    Signals.FulgoranRuinColossal,
    Signals.FulgoranRuinHuge,
    Signals.FulgoranRuinVault,
    Signals.FulgoranRuinAttractor,
    Signals.LithiumIcebergBig,
    Signals.LithiumIcebergHuge,
    Signals.SmallDemolisherCorpse,
    Signals.MediumDemolisherCorpse,
    Signals.BigDemolisherCorpse,
    Signals.CrudeOilDeposit,
    Signals.LithiumBrineDeposit,
    Signals.SulfuricAcidGeyser,
    Signals.FluorineVent,
    Signals.Lightning,
    Signals.Normal,
    Signals.Uncommon,
    Signals.Rare,
    Signals.Epic,
    Signals.Legendary,
    Signals.SignalAnyQuality,
    Signals.CopperWire,
    Signals.GreenWire,
    Signals.RedWire,
    Signals.SpidertronRemote,
    Signals.DischargeDefenseRemote,
    Signals.ArtilleryTargetingRemote,
    Signals.EntityGhost,
    Signals.ItemOnGround,
    Signals.ItemRequestProxy,
    Signals.TileGhost,
    Signals.WubeLogoSpacePlatform,
];
